version: "3"
services:
  rocky8build:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL8
  rocky8buildreloc:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL8

volumes:
  rpm8rocky:
    name: rpm8rocky
