version: "3"
services:
  stream9run:
    build:
      context: .
      dockerfile: Dockerfile.el9
      args:
        centos: $OS9
    image: "aursu/php83build:${OS9TAG}-runtime"
  stream9devbase:
    build:
      context: .
      dockerfile: Dockerfile.el9
      args:
        image: node18dev
        centos: $OS9
    image: "aursu/php83build:${OS9TAG}-devbase"
  stream9dev2base:
    build:
      context: .
      dockerfile: Dockerfile.el9
      args:
        image: node20dev
        centos: $OS9
    image: "aursu/php83build:${OS9TAG}-dev2base"